# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=512)),
                ('address_line2', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=512)),
                ('district', models.CharField(max_length=512)),
                ('taluka', models.CharField(max_length=512)),
                ('village', models.CharField(max_length=512, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_name', models.CharField(max_length=512)),
                ('gstn_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_token', models.CharField(default=b'10344e3e-8a6f-4161-ad3a-d3192da7e0f7', max_length=70, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('loggedout_time', models.DateTimeField(null=True)),
                ('is_logged_in', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('default_image', models.CharField(max_length=512, null=True)),
                ('features', models.CharField(max_length=512, null=True)),
                ('price', models.FloatField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('purchase_order_token', models.CharField(default=b'2c36ab4e-76d0-4e29-9591-487c47fdf6fd', max_length=70, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(max_length=10)),
                ('is_shipped', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(related_name='purchase_items', to='supplychainmodels.CartItem')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Hotel')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SellOrders',
            fields=[
                ('sell_order_token', models.CharField(default=b'308b6690-49b0-4fba-99ff-13810cc8e5ed', max_length=70, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(max_length=10)),
                ('is_shipped', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(related_name='sell_items', to='supplychainmodels.CartItem')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Farmer')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1024)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=512)),
                ('mobile', models.CharField(max_length=12)),
                ('pan_no', models.CharField(max_length=12)),
                ('account_no', models.CharField(max_length=15)),
                ('user_type', models.CharField(max_length=512)),
                ('photo', models.CharField(max_length=1024, null=True)),
                ('shipping_addresses', models.ManyToManyField(to='supplychainmodels.Address')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.User'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.User'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.User'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Product'),
        ),
    ]
