# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=512)),
                ('address_line2', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=512)),
                ('district', models.CharField(max_length=512)),
                ('taluka', models.CharField(max_length=512)),
                ('village', models.CharField(max_length=512, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_name', models.CharField(max_length=512)),
                ('gst_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('default_image', models.CharField(max_length=512, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=512)),
                ('mname', models.CharField(max_length=512)),
                ('lname', models.CharField(max_length=512)),
                ('mobile', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=512)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Address')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.User'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.User'),
        ),
    ]
