# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=10)),
                ('min_price', models.FloatField(max_length=10)),
                ('max_price', models.FloatField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.User')),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('name', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.Address')),
            ],
        ),
        migrations.AddField(
            model_name='farmerproductdetails',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychainmodels.WareHouse'),
        ),
    ]
