# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainmodels', '0002_auto_20190428_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorders',
            name='price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_item_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_token',
            field=models.CharField(default=b'262844bc-96a7-4308-a37d-51f4c27b0373', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='purchase_order_token',
            field=models.CharField(default=b'88e2784e-1e87-4150-b877-c6677c092e84', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='sell_order_token',
            field=models.CharField(default=b'b06851e2-39a7-49e0-ba2b-8a8324d35811', max_length=70, primary_key=True, serialize=False),
        ),
    ]
