# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychainmodels', '0003_auto_20190509_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='farmer',
            name='firm_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_item_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='login_token',
            field=models.CharField(default=b'678cf4ff-edea-4232-a6ea-ce249eb1a544', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='purchase_order_token',
            field=models.CharField(default=b'a173cd23-e5fd-439c-8550-0085b5a9b6fe', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellorders',
            name='sell_order_token',
            field=models.CharField(default=b'0f100d73-66e7-4092-b47e-1f23413d6c98', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
